services:
  db:
    image: mysql
    ports:
      - "3307:3306" 
    volumes:
      - ./mysql-data:/var/lib/mysql
    container_name: mysql_c
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - express_sequelize
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: express-app:tasin
    container_name: express_c
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_NAME: blog_server
      SERVER_NAME: root
      DB_PASSWORD: my-secret-pw
      PORT: 5000
    networks:
      - express_sequelize

networks:
  express_sequelize: